### ISSUE TITLE
where to insert div() in ioslides_presentation

### ISSUE THREAD

**Issue by ginolhac** [ijlyttle/vembedr#5]
A silly question, where am I supposed to put the `div` tag

if I do this, it is working well on `ioslides` (and actually centered)

``````
```{r, echo=FALSE}
library("vembedr")
suppressPackageStartupMessages(library("dplyr"))
embed_youtube("8SGif63VW6E")
``````

``````
This doesn't work, might do something stupid
```{r, echo=FALSE}
div(align = 'center', embed_youtube("8SGif63VW6E"))
``````

same if outside any `r chunk`

**Comment by ijlyttle** [comment]
I think the `div` tag can be useful in RMarkdown's `html_document()` and in Shiny. 

As you have found, `div` does not seem to be useful in `ioslides`. 

An earlier version of this function returned the `div` rather than the `iframe`, and I think your comment affirms that it was the right choice to return (more modestly) the `iframe`, then leave it to the user to put the `iframe` into the right container.
